version: '3.5'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8302:80"
            - "4402:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: larastorage_php
        user: "${UID}"
        volumes:
          - ./:/var/www
          - ./data/composer:/.composer
          - ./logs/laravel:/var/www/var/logs:cached
        depends_on:
            - mysql
            - redis
    redis:
        image: redis:latest
        ports:
          - "6302:6379"
    mysql:
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: discover9100Ylarastorage
            MYSQL_DATABASE: discover_storageapp
        ports:
            - "8902:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql